services:
  age:
    build: .
    ports:
      - 3000:3000

    depends_on: 
      db:
        condition: service_healthy
  db :
    image : mysql
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=sophie --password=sophie --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306" 
    environment : 
      MYSQL_USER: sophie
      MYSQL_ROOT_PASSWORD: sophie
      MYSQL_DATABASE: CUBE
      MYSQL_PASSWORD : sophie
    volumes : 
      - ./docker/db/data:/var/lib/mysql
