services:
  age:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db
  db :
    image : mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-usophie", "-psophie"]
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306" 
    environment : 
      MYSQL_USER: sophie
      MYSQL_ROOT_PASSWORD: sophie
      MYSQL_DATABASE: CUBE
      MYSQL_PASSWORD : sophie
  build-push-docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/sts076/cicd:${{ github.ref_name }}
