services:
  age:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db
      
  db :
    image : mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-usophie", "-psophie"]
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306" 
    environment : 
      MYSQL_USER: sophie
      MYSQL_ROOT_PASSWORD: sophie
      MYSQL_DATABASE: CUBE
      MYSQL_PASSWORD : sophie

    web:
      build: .
      ports:
        - "3000:3000"
      volumes:
        - .:/app
      command: npm run dev

