const swaggerAutogen = require("swagger-autogen")()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    // definitions: {
    //     user: {
    //         $name: "John",
    //         $surname: 'Doe',
    //         birthdate: 21 / 09 / 1992,
    //         city: 'Paris',
    //         address: 'rue de la paix',
    //         zip_code: 75000,
    //         department: 'Seine Maritime',
    //         email: 'john@doe.fr'

    //     },
    //     AddUser: {
    //         $name: "John",
    //         $surname: 'Doe',
    //         birthdate: 21 / 09 / 1992,
    //         city: 'Paris',
    //         address: 'rue de la paix',
    //         zip_code: 75000,
    //         department: 'Seine Maritime',
    //         email: 'john@doe.fr'
    //     }

    // }
}

const outputFile = "./swagger-output.json"
const endpointsFiles = ["./index.js"]

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require("./index.js")
})