on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Utilisez la version v2 de l'action
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Utilisez la version v2 de l'action
      - name: Install dependencies
        run: |
          npm install
          npm install request
      - name: Run tests
        run: npm run test
  eslint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Utilisez la version v2 de l'action
      - name: Install dependencies
        run: |
          npm install
          npm install eslint
      - name: Run eslint
        run: npm run lint
